language: python
virtualenv:
    system_site_packages: true
addons:
  apt:
    packages:
    - python3
    - python3-numpy
    - python3-scipy 
    - python3-matplotlib
script:
  - cd test/
  - ./run_tests.sh
