language: python
virtualenv:
    system_site_packages: true
install:
  - pip3 install
  - pip3 install numpy
  - pip3 install scipy 
  - pip3 install matplotlib
  - pip3 install nose
script:
  - nosetests3
